version: '3.8'

services:
  postgres:
    image: postgis/postgis:14-3.3
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:5.0
    restart: always
    volumes:
      - mongo_data:/data/db

  redis-main:
    image: redis:6-alpine
    restart: always
    volumes:
      - redis_main_data:/data

  redis-cache:
    image: redis:6-alpine
    restart: always
    volumes:
      - redis_cache_data:/data

  enketo:
    image: kobotoolbox/enketo-express:2.3.6
    restart: always
    depends_on:
      - redis-cache

  kpi:
    image: kobotoolbox/kpi:2.021.36a
    restart: always
    depends_on:
      - postgres
      - mongo
      - redis-main
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - MONGO_HOST=mongo
      - REDIS_HOST=redis-main
      - REDIS_PORT=6379
      - ALLOWED_HOSTS=*
      - ENKETO_URL=http://enketo:8005
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
      - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL}

  kobocat:
    image: kobotoolbox/kobocat:2.021.36a
    restart: always
    depends_on:
      - postgres
      - mongo
      - redis-main
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - MONGO_HOST=mongo
      - REDIS_HOST=redis-main
      - REDIS_PORT=6379
      - ALLOWED_HOSTS=*
      - ENKETO_URL=http://enketo:8005
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
      - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL}

  nginx:
    image: nginx:1.25-alpine
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - enketo
      - kpi
      - kobocat
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data:
  mongo_data:
  redis_main_data:
  redis_cache_data:
