version: '3.8'

services:
  postgres:
    image: postgis/postgis:14-3.3
    restart: always
    networks:
      - kobo-backend-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data

  mongo:
    image: mongo:5.0
    restart: always
    networks:
      - kobo-backend-network
    volumes:
      - mongo_data_volume:/data/db

  redis-main:
    image: redis:6-alpine
    restart: always
    networks:
      - kobo-backend-network
    volumes:
      - redis_main_data_volume:/data

  redis-cache:
    image: redis:6-alpine
    restart: always
    networks:
      - kobo-backend-network
    volumes:
      - redis_cache_data_volume:/data

  enketo:
    image: kobotoolbox/enketo-express:custom-confirmation-message
    restart: always
    networks:
      - kobo-frontend-network
      - kobo-backend-network
    depends_on:
      - redis-cache

  kpi:
    image: kobotoolbox/kpi:2.025.34b
    restart: always
    networks:
      - kobo-frontend-network
      - kobo-backend-network
    depends_on:
      - postgres
      - mongo
      - redis-main
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      MONGO_HOST: ${MONGO_HOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
      AWS_S3_REGION_NAME: ${AWS_S3_REGION_NAME}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}

  kobocat:
    image: kobotoolbox/kobocat:2.024.19e
    restart: always
    networks:
      - kobo-frontend-network
      - kobo-backend-network
    depends_on:
      - postgres
      - mongo
      - redis-main
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      MONGO_HOST: ${MONGO_HOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
      AWS_S3_REGION_NAME: ${AWS_S3_REGION_NAME}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}

  nginx:
    image: nginx:1.25-alpine
    restart: always
    ports:
      - "8081:80"
    networks:
      - kobo-frontend-network
      - kobo-backend-network
    depends_on:
      - enketo
      - kpi
      - kobocat

networks:
  kobo-frontend-network:
  kobo-backend-network:

volumes:
  postgres_data_volume:
  mongo_data_volume:
  redis_main_data_volume:
  redis_cache_data_volume:
