version: '3.8'

networks:
  kobo-frontend-network:
    driver: bridge
  kobo-backend-network:
    driver: bridge

volumes:
  postgres_data_volume:
  mongo_data_volume:
  redis_main_data_volume:
  redis_cache_data_volume:
  kpi_media_volume:
  kobocat_media_volume:

services:
  postgres:
    image: postgis/postgis:14-3.3
    container_name: kobo-postgres
    restart: always
    networks:
      - kobo-backend-network
    environment:
      - POSTGRES_USER=kobo
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - KOBO_DB_NAME=${KOBO_DB_NAME}
      - KOBO_DB_USER=${KOBO_DB_USER}
      - KOBO_DB_PASSWORD=${KOBO_USER_PASSWORD}
      - KOBOCAT_DB_NAME=${KOBOCAT_DB_NAME}
      - KOBOCAT_DB_USER=${KOBOCAT_DB_USER}
      - KOBOCAT_DB_PASSWORD=${KOBOCAT_USER_PASSWORD}
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data

  mongo:
    image: mongo:5.0
    container_name: kobo-mongo
    restart: always
    networks:
      - kobo-backend-network
    volumes:
      - mongo_data_volume:/data/db

  redis-main:
    image: redis:6-alpine
    container_name: kobo-redis-main
    restart: always
    networks:
      - kobo-backend-network
    volumes:
      - redis_main_data_volume:/data

  redis-cache:
    image: redis:6-alpine
    container_name: kobo-redis-cache
    restart: always
    networks:
      - kobo-backend-network
    volumes:
      - redis_cache_data_volume:/data

  kpi:
    image: kobotoolbox/kpi:2.025.34b
    container_name: kpi
    restart: always
    networks:
      - kobo-frontend-network
      - kobo-backend-network
    environment:
      - KPI_DATABASE_URL=postgres://${KOBO_DB_USER}:${KOBO_USER_PASSWORD}@postgres:5432/${KOBO_DB_NAME}
      - MONGODB_DATABASE=kobofe
      - MONGODB_HOST=mongo
      - REDIS_HOST=redis-cache
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
    depends_on:
      - postgres
      - mongo
      - redis-cache
    volumes:
      - kpi_media_volume:/srv/src/kpi/media

  kobocat:
    image: kobotoolbox/kobocat:2.024.19e
    container_name: kobocat
    restart: always
    networks:
      - kobo-frontend-network
      - kobo-backend-network
    environment:
      - KOBOCAT_DATABASE_URL=postgres://${KOBOCAT_DB_USER}:${KOBOCAT_USER_PASSWORD}@postgres:5432/${KOBOCAT_DB_NAME}
      - MONGODB_DATABASE=kobofe
      - MONGODB_HOST=mongo
      - REDIS_HOST=redis-cache
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY_2}
    depends_on:
      - postgres
      - mongo
      - redis-cache
    volumes:
      - kobocat_media_volume:/srv/src/kobocat/media

  enketo:
    image: kobotoolbox/enketo-express:custom-confirmation-message
    container_name: enketo
    restart: always
    networks:
      - kobo-frontend-network
      - kobo-backend-network
    environment:
      - ENKETO_API_TOKEN=${ENKETO_API_TOKEN}
      - ENKETO_SECRET=${ENKETO_SECRET}
      - REDIS_URL=redis://redis-main:6379
      - ENKETO_REDIS_MAIN=redis://redis-main:6379
      - ENKETO_REDIS_CACHE=redis://redis-cache:6379
      - REDIS_CACHE_URL=redis://redis-cache:6379
    depends_on:
      - redis-main
      - redis-cache

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    restart: always
    networks:
      - kobo-frontend-network
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - kpi
      - kobocat
      - enketo
